<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require __DIR__.'/includes/public-layout.php';
require __DIR__.'/includes/mercado.php';
require __DIR__.'/includes/elenco-geral.php';
if(!account_logged_in()){header('Location: login.php');exit;} if(account_must_change_password()){header('Location: trocar-senha.php');exit;}
$sessionParticipantId=(int)(account_participant_id()??0);$requested=(int)($_REQUEST['participante_id']??0);$participantId=account_is_master()&&$requested>0?$requested:$sessionParticipantId;
if($participantId<1){http_response_code(403);exit('Sua conta precisa estar vinculada a um time.');}
$pdo=db();$message=(string)($_SESSION['elenco_geral_mensagem']??'');unset($_SESSION['elenco_geral_mensagem']);$error='';
try{
 elenco_geral_garantir_estrutura($pdo);$s=$pdo->prepare('SELECT time_nome,nome FROM participantes WHERE id=? AND ativo=1');$s->execute([$participantId]);$time=$s->fetch();if(!$time)throw new RuntimeException('Clube não encontrado.');
 if($_SERVER['REQUEST_METHOD']==='POST'){
  verify_csrf();$action=(string)($_POST['action']??'');if(!in_array($action,['comprar_geral','vender_geral','atualizar_cofre_geral','editar_jogador_geral','editar_movimentacao_geral','desfazer_movimentacao_geral'],true))throw new RuntimeException('Ação inválida.');
  $pdo->beginTransaction();$clube=elenco_geral_clube($pdo,$participantId,true);if($action!=='atualizar_cofre_geral'&&!(bool)$clube['cofre_configurado'])throw new RuntimeException('Configure primeiro o cofre do clube na área de transferências.');$antes=(float)$clube['saldo'];
  if($action==='atualizar_cofre_geral'){
   $saldo=mercado_parse_valor((string)($_POST['saldo']??'0'));if($saldo<0)throw new RuntimeException('O saldo do cofre não pode ser negativo.');
   $pdo->prepare('UPDATE clubes_gerais SET saldo=?,cofre_configurado=1 WHERE id=?')->execute([$saldo,$clube['id']]);$pdo->prepare('UPDATE clubes_campeonato SET saldo=?,cofre_configurado=1 WHERE participante_id=?')->execute([$saldo,$participantId]);$message='Saldo do cofre atualizado.';
  }elseif($action==='editar_jogador_geral'){
   $jogadorId=(int)($_POST['jogador_id']??0);$nome=trim((string)($_POST['nome']??''));
   if($nome===''||mb_strlen($nome)>150)throw new RuntimeException('Informe o nome exato do jogador, com até 150 caracteres.');
   $s=$pdo->prepare('SELECT * FROM jogadores_gerais WHERE id=? AND participante_id=? AND ativo=1 FOR UPDATE');$s->execute([$jogadorId,$participantId]);$j=$s->fetch();if(!$j)throw new RuntimeException('Jogador não encontrado.');
   $pdo->prepare('UPDATE jogadores_gerais SET nome=? WHERE id=?')->execute([$nome,$jogadorId]);$pdo->prepare('UPDATE jogadores_elenco SET nome=? WHERE jogador_geral_id=? AND participante_id=? AND ativo=1')->execute([$nome,$jogadorId,$participantId]);$pdo->prepare('UPDATE movimentacoes_elenco_geral SET jogador_nome=?,conta_id=? WHERE jogador_geral_id=? AND participante_id=?')->execute([$nome,(int)$_SESSION['conta_id'],$jogadorId,$participantId]);$message='Nome atualizado em todo o elenco: '.$nome.'.';
  }elseif(in_array($action,['editar_movimentacao_geral','desfazer_movimentacao_geral'],true)){
   $movimentoId=(int)($_POST['movimentacao_id']??0);$s=$pdo->prepare('SELECT * FROM movimentacoes_elenco_geral WHERE id=? AND participante_id=? FOR UPDATE');$s->execute([$movimentoId,$participantId]);$m=$s->fetch();if(!$m)throw new RuntimeException('Movimentação não encontrada.');$s=$pdo->prepare('SELECT * FROM jogadores_gerais WHERE id=? AND participante_id=? FOR UPDATE');$s->execute([(int)$m['jogador_geral_id'],$participantId]);$j=$s->fetch();if(!$j)throw new RuntimeException('Jogador da movimentação não encontrado.');$s=$pdo->prepare('SELECT COUNT(*) FROM movimentacoes_elenco_geral WHERE jogador_geral_id=? AND id>?');$s->execute([(int)$m['jogador_geral_id'],$movimentoId]);if((int)$s->fetchColumn()>0)throw new RuntimeException('Edite ou desfaça primeiro as movimentações mais recentes deste jogador.');
   if($action==='desfazer_movimentacao_geral'){
    if($m['tipo']==='compra'){if(!(bool)$j['ativo'])throw new RuntimeException('Esta contratação já não pode ser desfeita porque o jogador saiu do elenco.');$depois=$antes+(float)$m['valor'];$pdo->prepare('UPDATE jogadores_gerais SET ativo=0,saiu_em=NOW() WHERE id=?')->execute([$j['id']]);$pdo->prepare('UPDATE jogadores_elenco SET ativo=0,saiu_em=NOW() WHERE jogador_geral_id=? AND ativo=1')->execute([$j['id']]);}else{if((bool)$j['ativo'])throw new RuntimeException('Esta venda já foi desfeita.');$depois=$antes-(float)$m['valor'];if($depois<0)throw new RuntimeException('Não é possível desfazer a venda porque o cofre ficaria negativo.');$pdo->prepare('UPDATE jogadores_gerais SET ativo=1,saiu_em=NULL WHERE id=?')->execute([$j['id']]);}
    $pdo->prepare('UPDATE clubes_gerais SET saldo=? WHERE id=?')->execute([$depois,$clube['id']]);$pdo->prepare('UPDATE clubes_campeonato SET saldo=? WHERE participante_id=?')->execute([$depois,$participantId]);$pdo->prepare('DELETE FROM movimentacoes_elenco_geral WHERE id=?')->execute([$movimentoId]);$message=$m['tipo']==='compra'?'Contratação desfeita e cofre corrigido.':'Venda desfeita; o jogador voltou ao Elenco Geral e o cofre foi corrigido.';
   }else{
    $nome=trim((string)($_POST['nome']??''));$overall=(int)($_POST['overall']??0);$posicao=(string)($_POST['posicao']??'');$origem=$m['tipo']==='venda'?'venda':(string)($_POST['origem']??'compra_direta');if($nome===''||mb_strlen($nome)>150||$overall<1||$overall>99||!in_array($posicao,MERCADO_POSICOES,true))throw new RuntimeException('Preencha corretamente os dados do jogador.');if($m['tipo']==='compra'&&!in_array($origem,['compra_direta','pack','passe','sorteio','prancheta','obter'],true))throw new RuntimeException('Origem inválida.');$valor=($m['tipo']==='venda'||$origem==='compra_direta')?mercado_parse_valor((string)($_POST['valor']??'0')):0.0;$detalhe=null;$valorOrigem=null;$moeda=null;
    if($origem==='pack'){$packId=(string)($_POST['pack']??'');if(!isset(MERCADO_PACKS[$packId]))throw new RuntimeException('Selecione o pack.');$pack=MERCADO_PACKS[$packId];if($overall<$pack['min']||$overall>$pack['max'])throw new RuntimeException('OVR fora da faixa do pack.');$detalhe=$pack['nome'];$valorOrigem=$pack['dream_points'];$moeda='DP';}$impactoAntigo=$m['tipo']==='venda'?(float)$m['valor']:-(float)$m['valor'];$impactoNovo=$m['tipo']==='venda'?$valor:-$valor;$depois=$antes+$impactoNovo-$impactoAntigo;if($depois<0)throw new RuntimeException('Saldo insuficiente para esta correção.');
    $pdo->prepare('UPDATE jogadores_gerais SET nome=?,overall=?,posicao=? WHERE id=?')->execute([$nome,$overall,$posicao,$j['id']]);$pdo->prepare('UPDATE jogadores_elenco SET nome=?,overall=?,posicao=? WHERE jogador_geral_id=? AND ativo=1')->execute([$nome,$overall,$posicao,$j['id']]);$pdo->prepare('UPDATE movimentacoes_elenco_geral SET origem=?,origem_detalhe=?,valor_origem=?,moeda_origem=?,jogador_nome=?,jogador_overall=?,jogador_posicao=?,valor=?,saldo_posterior=?,conta_id=? WHERE id=?')->execute([$origem,$detalhe,$valorOrigem,$moeda,$nome,$overall,$posicao,$valor,$depois,(int)$_SESSION['conta_id'],$movimentoId]);$pdo->prepare('UPDATE clubes_gerais SET saldo=? WHERE id=?')->execute([$depois,$clube['id']]);$pdo->prepare('UPDATE clubes_campeonato SET saldo=? WHERE participante_id=?')->execute([$depois,$participantId]);$message='Movimentação e jogador corrigidos com sucesso.';
   }
  }elseif($action==='comprar_geral'){
   $nome=trim((string)($_POST['nome']??''));$overall=(int)($_POST['overall']??0);$posicao=(string)($_POST['posicao']??'');$origem=(string)($_POST['origem']??'compra_direta');
   if($nome===''||$overall<1||$overall>99||!in_array($posicao,MERCADO_POSICOES,true))throw new RuntimeException('Preencha corretamente os dados do jogador.');if(!in_array($origem,['compra_direta','pack','passe','sorteio','prancheta','obter'],true))throw new RuntimeException('Origem inválida.');
   $valor=$origem==='compra_direta'?mercado_parse_valor((string)($_POST['valor']??'')):0.0;if($valor>$antes)throw new RuntimeException('Saldo insuficiente.');$detalhe=null;$valorOrigem=null;$moeda=null;
   if($origem==='pack'){$packId=(string)($_POST['pack']??'');if(!isset(MERCADO_PACKS[$packId]))throw new RuntimeException('Selecione o pack.');$pack=MERCADO_PACKS[$packId];if($overall<$pack['min']||$overall>$pack['max'])throw new RuntimeException('OVR fora da faixa do pack.');$detalhe=$pack['nome'];$valorOrigem=$pack['dream_points'];$moeda='DP';}
   $s=$pdo->prepare('INSERT INTO jogadores_gerais(participante_id,nome,overall,posicao) VALUES(?,?,?,?)');$s->execute([$participantId,$nome,$overall,$posicao]);$jogadorId=(int)$pdo->lastInsertId();$depois=$antes-$valor;
   $pdo->prepare('UPDATE clubes_gerais SET saldo=? WHERE id=?')->execute([$depois,$clube['id']]);$pdo->prepare('UPDATE clubes_campeonato SET saldo=? WHERE participante_id=?')->execute([$depois,$participantId]);$pdo->prepare("INSERT INTO movimentacoes_elenco_geral(participante_id,jogador_geral_id,tipo,origem,origem_detalhe,valor_origem,moeda_origem,jogador_nome,jogador_overall,jogador_posicao,valor,saldo_anterior,saldo_posterior,conta_id) VALUES(?,?,'compra',?,?,?,?,?,?,?,?,?,?,?)")->execute([$participantId,$jogadorId,$origem,$detalhe,$valorOrigem,$moeda,$nome,$overall,$posicao,$valor,$antes,$depois,(int)$_SESSION['conta_id']]);$message="$nome entrou somente no Elenco Geral.";
  }else{
   $jogadorId=(int)($_POST['jogador_id']??0);$valor=mercado_parse_valor((string)($_POST['valor']??''));$s=$pdo->prepare('SELECT * FROM jogadores_gerais WHERE id=? AND participante_id=? AND ativo=1 FOR UPDATE');$s->execute([$jogadorId,$participantId]);$j=$s->fetch();if(!$j)throw new RuntimeException('Jogador não encontrado.');
   $s=$pdo->prepare("SELECT DISTINCT e.campeonato_id,c.nome,c.tipo FROM jogadores_elenco e JOIN campeonatos c ON c.id=e.campeonato_id WHERE e.jogador_geral_id=? AND e.ativo=1");$s->execute([$jogadorId]);foreach($s->fetchAll() as $i){if($i['tipo']==='pontos_corridos'&&!mercado_estado_clube($pdo,(int)$i['campeonato_id'],$participantId)['aberto'])throw new RuntimeException($j['nome'].' está inscrito em '.$i['nome'].', cujo ciclo está fechado.');}
   $depois=$antes+$valor;$pdo->prepare('UPDATE jogadores_gerais SET ativo=0,saiu_em=NOW() WHERE id=?')->execute([$jogadorId]);$pdo->prepare('UPDATE jogadores_elenco SET ativo=0,saiu_em=NOW() WHERE jogador_geral_id=? AND ativo=1')->execute([$jogadorId]);$pdo->prepare('UPDATE clubes_gerais SET saldo=? WHERE id=?')->execute([$depois,$clube['id']]);$pdo->prepare('UPDATE clubes_campeonato SET saldo=? WHERE participante_id=?')->execute([$depois,$participantId]);$pdo->prepare("INSERT INTO movimentacoes_elenco_geral(participante_id,jogador_geral_id,tipo,origem,jogador_nome,jogador_overall,jogador_posicao,valor,saldo_anterior,saldo_posterior,conta_id) VALUES(?,?,'venda','venda',?,?,?,?,?,?,?)")->execute([$participantId,$jogadorId,$j['nome'],$j['overall'],$j['posicao'],$valor,$antes,$depois,(int)$_SESSION['conta_id']]);$message=$j['nome'].' foi vendido.';
  }$pdo->commit();
 }
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof PDOException&&$e->getCode()==='23000'?'Este jogador já está no Elenco Geral.':$e->getMessage();}
try{$jogadores=elenco_geral_do_clube($pdo,$participantId);$clube=elenco_geral_clube($pdo,$participantId);$s=$pdo->prepare("SELECT id,jogador_geral_id,tipo,origem,origem_detalhe,valor_origem,moeda_origem,jogador_nome,jogador_overall,jogador_posicao,valor,criado_em,NULL campeonato,'geral' fonte FROM movimentacoes_elenco_geral WHERE participante_id=? UNION ALL SELECT m.id,m.jogador_id,m.tipo,m.origem,m.origem_detalhe,m.valor_origem,m.moeda_origem,m.jogador_nome,m.jogador_overall,m.jogador_posicao,m.valor,m.criado_em,c.nome,'competicao' fonte FROM movimentacoes_elenco m JOIN campeonatos c ON c.id=m.campeonato_id WHERE m.participante_id=? ORDER BY criado_em DESC");$s->execute([$participantId,$participantId]);$historico=$s->fetchAll();$bloqueiosVenda=[];$s=$pdo->prepare("SELECT DISTINCT e.jogador_geral_id,e.campeonato_id,c.nome FROM jogadores_elenco e JOIN campeonatos c ON c.id=e.campeonato_id WHERE e.participante_id=? AND e.ativo=1 AND e.jogador_geral_id IS NOT NULL AND c.tipo='pontos_corridos'");$s->execute([$participantId]);foreach($s->fetchAll() as $vinculo){if(!mercado_estado_clube($pdo,(int)$vinculo['campeonato_id'],$participantId)['aberto'])$bloqueiosVenda[(int)$vinculo['jogador_geral_id']][]=$vinculo['nome'];}}catch(Throwable $e){$jogadores=[];$historico=[];$bloqueiosVenda=[];$clube=['saldo'=>0];if(!$error)$error='Não foi possível carregar o Elenco Geral.';}
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Elenco Geral | <?=e((string)($time['time_nome']??'Clube'))?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css?v=<?=filemtime(__DIR__.'/assets/css/style.css')?>"><link rel="stylesheet" href="assets/css/branding.css?v=5"><link rel="stylesheet" href="assets/css/elenco-geral.css?v=<?=filemtime(__DIR__.'/assets/css/elenco-geral.css')?>"></head><body><?php public_navbar('elenco-geral');?><main class="general-roster-page"><div class="container">
<header class="general-roster-hero"><div><span class="eyebrow">Patrimônio do clube</span><h1>ELENCO GERAL</h1><p><?=e((string)($time['time_nome']??''))?> · <?=count($jogadores)?> jogadores · sem limite máximo</p></div><button class="general-balance" type="button" data-bs-toggle="modal" data-bs-target="#general-treasury-modal" aria-label="Editar saldo do cofre"><span>COFRE DO CLUBE</span><strong>R$ <?=number_format((float)$clube['saldo'],0,',','.')?></strong><span class="general-balance-edit" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M4 20h4L19 9l-4-4L4 16v4Zm12.5-16.5 4 4 1-1a2.1 2.1 0 0 0 0-3l-1-1a2.1 2.1 0 0 0-3 0l-1 1Z"/></svg></span></button></header><?php if($message):?><div class="alert alert-success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;?>
<a class="general-import-banner" href="importar-elenco.php<?=account_is_master()&&$participantId!==$sessionParticipantId?'?participante_id='.$participantId:''?>"><span><small>Importação rápida</small><strong>IMPORTAR ELENCO</strong><em>Cole a lista do Discord e adicione os jogadores ao Elenco Geral.</em></span><b>Começar importação →</b></a>
<section class="general-flow-grid" aria-label="Como funciona o fluxo de jogadores"><article><span>01</span><div><strong>Obtenha jogadores</strong><p>Contrate manualmente ou importe a lista do Discord. Todo jogador entra primeiro no Elenco Geral.</p></div></article><article><span>02</span><div><strong>Espere a janela</strong><p>Se uma competição estiver travada, o novo jogador permanece seguro no Geral e não altera a inscrição atual.</p></div></article><article><span>03</span><div><strong>Inscreva na competição</strong><p>Quando a janela abrir, todos os jogadores do Geral aparecerão automaticamente na Gestão da Competição para você escolher.</p></div></article><article><span>04</span><div><strong>Venda quando estiver livre</strong><p>Jogador somente no Geral pode ser vendido. Se estiver inscrito em pontos corridos com ciclo fechado, a própria tela explica o bloqueio.</p></div></article></section>
<div class="alert alert-info general-guidance"><strong>Elenco Geral é o patrimônio do clube.</strong> Contratar, importar ou vender aqui nunca troca sozinho os 11 titulares de uma competição.</div>
<section class="panel p-4 mb-4"><span class="eyebrow">Sempre disponível</span><h2>CONTRATAR PARA O ELENCO GERAL</h2><p class="text-secondary">Entra somente no Geral. Nenhuma competição travada recebe o jogador.</p><form method="post" class="row g-3"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="comprar_geral"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><div class="col-lg-4"><label class="form-label">Nome completo</label><input class="form-control" name="nome" required></div><div class="col-6 col-lg-2"><label class="form-label">OVR</label><input class="form-control" type="number" min="1" max="99" name="overall" required></div><div class="col-6 col-lg-2"><label class="form-label">Posição</label><select class="form-select" name="posicao"><?php foreach(MERCADO_POSICOES as $p):?><option><?=e($p)?></option><?php endforeach;?></select></div><div class="col-lg-4"><label class="form-label">Origem</label><select class="form-select" name="origem"><option value="compra_direta">Compra direta</option><option value="pack">Recebido em pack</option><option value="passe">Recebido no passe</option><option value="sorteio">Ganho em sorteio</option><option value="prancheta">Recebido pela prancheta</option><option value="obter">Recebido pelo /obter</option></select></div><div class="col-lg-6 general-pack-field" hidden><label class="form-label">Pack</label><select class="form-select" name="pack"><option value="">Selecione</option><?php foreach(MERCADO_PACKS as $id=>$pack):?><option value="<?=e($id)?>"><?=e($pack['nome'])?> · <?=$pack['min']?>–<?=$pack['max']?> OVR</option><?php endforeach;?></select></div><div class="col-lg-4 general-value-field"><label class="form-label">Valor</label><input class="form-control" type="number" min="0" name="valor" required></div><div class="col-lg-2 d-flex align-items-end"><button class="btn btn-danger w-100">Contratar</button></div></form></section>
<section class="panel p-4 mb-4"><div class="general-list-heading"><div><span class="eyebrow">Todos os jogadores</span><h2>JOGADORES DO CLUBE</h2></div><div class="general-roster-filters"><input class="form-control" type="search" placeholder="Buscar pelo nome" data-roster-search><select class="form-select" data-roster-position><option value="">Todas as posições</option><?php foreach(MERCADO_POSICOES as $p):?><option><?=e($p)?></option><?php endforeach;?></select></div></div><div class="general-player-list" data-roster-list><?php foreach($jogadores as $j):$travado=$bloqueiosVenda[(int)$j['id']]??[];?><article class="general-player-row" data-name="<?=e(mb_strtolower($j['nome'],'UTF-8'))?>" data-position="<?=e($j['posicao'])?>"><span><?=e($j['posicao'])?></span><div><strong><?=e($j['nome'])?></strong><?php if($travado):?><small class="general-sale-lock">Venda bloqueada: inscrito em <?=e(implode(', ',$travado))?> com ciclo fechado.</small><?php else:?><small class="general-sale-free">Disponível para venda.</small><?php endif;?></div><b><?=(int)$j['overall']?> OVR</b><div class="general-player-buttons"><button class="btn btn-sm btn-outline-light" type="button" data-edit-player data-player-id="<?=(int)$j['id']?>" data-player-name="<?=e($j['nome'])?>">Editar</button><?php if($travado):?><button class="btn btn-sm btn-outline-secondary" type="button" disabled title="Aguarde a janela da competição abrir">Não pode vender</button><?php else:?><button class="btn btn-sm btn-outline-danger" type="button" data-sell-player data-player-id="<?=(int)$j['id']?>" data-player-name="<?=e($j['nome'])?>">Vender</button><?php endif;?></div></article><?php endforeach;?></div><p data-roster-empty hidden>Nenhum jogador encontrado.</p><nav class="general-pagination" data-roster-pagination></nav></section>
<section class="panel p-4 general-history"><div class="general-list-heading"><div><span class="eyebrow">Movimentações do clube</span><h2>HISTÓRICO</h2></div><span class="text-secondary"><?=count($historico)?> registro(s)</span></div><div class="general-history-list" data-general-history><?php foreach($historico as $m):$packMovimento='';foreach(MERCADO_PACKS as $packId=>$packDados){if(($m['origem_detalhe']??'')===$packDados['nome']){$packMovimento=$packId;break;}}?><article><span class="history-kind <?=$m['tipo']==='compra'?'is-purchase':'is-sale'?>"><?=e(mercado_rotulo_origem($m))?></span><div><strong><?=e($m['jogador_nome'])?></strong><small><?=(int)$m['jogador_overall']?> · <?=e($m['jogador_posicao'])?><?=!empty($m['campeonato'])?' · '.e($m['campeonato']):''?> · <?=e(format_datetime_br((string)$m['criado_em']))?></small></div><b><?=e(mercado_valor_movimento($m))?></b><?php if($m['fonte']==='geral'):?><div class="general-history-actions"><button type="button" class="btn btn-sm btn-outline-light" data-edit-general-movement data-movement-id="<?=(int)$m['id']?>" data-movement-type="<?=e($m['tipo'])?>" data-player-name="<?=e($m['jogador_nome'])?>" data-player-overall="<?=(int)$m['jogador_overall']?>" data-player-position="<?=e($m['jogador_posicao'])?>" data-movement-origin="<?=e($m['origem'])?>" data-movement-pack="<?=e($packMovimento)?>" data-movement-value="<?=(float)$m['valor']?>">Editar</button><button type="button" class="btn btn-sm btn-outline-danger" data-undo-general-movement data-movement-id="<?=(int)$m['id']?>" data-movement-type="<?=e($m['tipo'])?>" data-player-name="<?=e($m['jogador_nome'])?>">Desfazer</button></div><?php endif;?></article><?php endforeach;?></div><?php if(!$historico):?><p class="text-secondary mb-0">Nenhuma movimentação registrada.</p><?php endif;?><nav class="general-pagination" data-history-pagination></nav></section></div></main>
<div class="modal fade" id="general-sale-modal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h2>VENDER JOGADOR</h2><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="vender_geral"><input type="hidden" name="jogador_id"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><p>Vender <strong data-sale-name></strong>?</p><input class="form-control" type="number" min="0" name="valor" placeholder="Valor da venda" required><small class="text-secondary">Bloqueado somente se estiver inscrito em pontos corridos com ciclo fechado.</small></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Vender</button></div></form></div></div></div>
<div class="modal fade general-dark-modal" id="general-player-edit-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><div><small class="eyebrow">Nome oficial da carta</small><h2>EDITAR JOGADOR</h2></div><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="editar_jogador_geral"><input type="hidden" name="jogador_id"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><div class="alert alert-warning"><strong>AVISO: COPIE EXATAMENTE O NOME DA CARTA</strong><p class="mb-0 mt-2">No Discord, use <strong>/show</strong> para exibir a carta do jogador. Copie o nome exatamente como aparece no bot, incluindo acentos, espaços e sobrenomes, e cole abaixo. Isso permite que a súmula reconheça o jogador corretamente.</p></div><label class="form-label" for="general-player-edit-name">Nome exato no bot do Discord</label><input class="form-control form-control-lg" id="general-player-edit-name" name="nome" maxlength="150" required autocomplete="off"></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Salvar nome</button></div></form></div></div></div>
<div class="modal fade general-dark-modal" id="general-movement-edit-modal" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><form method="post"><div class="modal-header"><div><small class="eyebrow">Corrigir compra ou venda</small><h2>EDITAR MOVIMENTAÇÃO</h2></div><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="editar_movimentacao_geral"><input type="hidden" name="movimentacao_id"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><div class="row g-3"><div class="col-12"><label class="form-label">Jogador</label><input class="form-control" name="nome" maxlength="150" required></div><div class="col-6"><label class="form-label">OVR</label><input class="form-control" type="number" min="1" max="99" name="overall" required></div><div class="col-6"><label class="form-label">Posição</label><select class="form-select" name="posicao"><?php foreach(MERCADO_POSICOES as $p):?><option value="<?=e($p)?>"><?=e($p)?></option><?php endforeach;?></select></div><div class="col-12 general-movement-origin"><label class="form-label">Origem</label><select class="form-select" name="origem"><option value="compra_direta">Compra direta</option><option value="pack">Recebido em pack</option><option value="passe">Recebido no passe</option><option value="sorteio">Ganho em sorteio</option><option value="prancheta">Recebido pela prancheta</option><option value="obter">Recebido pelo /obter</option></select></div><div class="col-12 general-movement-pack" hidden><label class="form-label">Pack</label><select class="form-select" name="pack"><option value="">Selecione</option><?php foreach(MERCADO_PACKS as $id=>$pack):?><option value="<?=e($id)?>"><?=e($pack['nome'])?> · <?=$pack['min']?>–<?=$pack['max']?> OVR</option><?php endforeach;?></select></div><div class="col-12 general-movement-value"><label class="form-label">Valor em reais</label><input class="form-control" type="number" min="0" name="valor" required></div><div class="col-12"><div class="alert alert-info mb-0">A correção atualiza o jogador, as inscrições ativas e a diferença no cofre.</div></div></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Salvar correção</button></div></form></div></div></div>
<div class="modal fade general-dark-modal" id="general-movement-undo-modal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><div><small class="eyebrow">Reverter operação</small><h2>DESFAZER MOVIMENTAÇÃO</h2></div><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="desfazer_movimentacao_geral"><input type="hidden" name="movimentacao_id"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><p data-general-undo-copy></p><div class="alert alert-warning mb-0" data-general-undo-detail></div></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Voltar</button><button class="btn btn-danger">Sim, desfazer</button></div></form></div></div></div>
<div class="modal fade" id="general-treasury-modal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form method="post"><div class="modal-header"><h2>EDITAR COFRE</h2><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Fechar"></button></div><div class="modal-body"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="atualizar_cofre_geral"><?php if(account_is_master()&&$participantId!==$sessionParticipantId):?><input type="hidden" name="participante_id" value="<?=$participantId?>"><?php endif;?><label class="form-label" for="general-treasury-value">Saldo do cofre</label><div class="input-group"><span class="input-group-text">R$</span><input class="form-control" id="general-treasury-value" name="saldo" inputmode="numeric" value="<?=e(number_format((float)$clube['saldo'],0,',','.'))?>" required></div><small class="text-secondary">A correção também será refletida nas competições do clube. A edição continua disponível no perfil.</small></div><div class="modal-footer"><button type="button" class="btn btn-outline-light" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-danger">Salvar cofre</button></div></form></div></div></div><?php public_footer();?><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script><script src="assets/js/elenco-geral.js?v=<?=filemtime(__DIR__.'/assets/js/elenco-geral.js')?>"></script></body></html>
