<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require __DIR__.'/includes/public-layout.php';
$identities=[];$titles=[];
try {
    $pdo=db(); competition_identities_seed($pdo);
    $identities=$pdo->query("SELECT i.id,i.chave,i.nome FROM competicao_identidades i WHERE COALESCE(i.trofeu_base64,'')<>'' ORDER BY i.nome")->fetchAll();
    $titles=$pdo->query("SELECT t.id,t.titulo,t.temporada,t.conquistado_em,COALESCE(p.nome,t.tecnico_nome) tecnico,COALESCE(p.time_nome,t.time_nome) clube,p.escudo_url FROM titulos t LEFT JOIN participantes p ON p.id=t.participante_id ORDER BY t.conquistado_em DESC,t.id DESC")->fetchAll();
} catch(Throwable $ignored) {}
$grouped=[];
foreach($titles as $title){$key=competition_identity_match((string)$title['titulo']);if($key)$grouped[$key][]=$title;}
?><!doctype html><html lang="pt-BR" data-bs-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vitrine de Títulos | Vascão S3</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/branding.css?v=5"><link rel="stylesheet" href="assets/css/titles-showcase.css?v=<?= filemtime(__DIR__.'/assets/css/titles-showcase.css') ?>"></head><body>
<?php public_navbar('titulos'); ?>
<main class="titles-page"><div class="container"><header class="titles-hero"><span class="eyebrow">Salão de conquistas</span><h1>VITRINE DE TAÇAS</h1><p>Cada competição tem sua própria história. Explore as taças em tamanho grande e revele os campeões de todas as edições.</p></header><section class="trophy-showcase">
<?php foreach($identities as $identity): $champions=$grouped[$identity['chave']]??[]; ?><article class="trophy-card"><div class="trophy-stage"><img src="api/competicao-imagem.php?identidade_id=<?= (int)$identity['id'] ?>&tipo=trofeu" alt="Taça <?= e($identity['nome']) ?>"></div><div class="trophy-copy"><img class="trophy-logo" src="api/competicao-imagem.php?identidade_id=<?= (int)$identity['id'] ?>&tipo=logo" alt="Logo <?= e($identity['nome']) ?>"><h2><?= e($identity['nome']) ?></h2><small class="text-secondary"><?= count($champions) ?> título<?= count($champions)===1?'':'s' ?> registrado<?= count($champions)===1?'':'s' ?></small><button class="btn btn-outline-light show-champions" type="button" data-key="<?= e($identity['chave']) ?>" data-name="<?= e($identity['nome']) ?>">VER CAMPEÕES</button></div></article><?php endforeach; ?>
</section></div></main>
<div class="modal fade champions-modal" id="champions-modal" tabindex="-1" aria-labelledby="champions-modal-title" aria-hidden="true"><div class="modal-dialog modal-lg modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><div><small class="eyebrow">Galeria de vencedores</small><h2 class="modal-title" id="champions-modal-title">CAMPEÕES</h2></div><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Fechar"></button></div><div class="modal-body"><div id="champions-modal-list" class="champions-modal-list"></div></div></div></div></div>
<?php public_footer(); ?>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script><script>const champions=<?= json_encode($grouped,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>,escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char])),initials=value=>String(value||'?').split(/\s+/).slice(0,2).map(word=>word[0]||'').join('').toUpperCase(),modalElement=document.getElementById('champions-modal'),modal=bootstrap.Modal.getOrCreateInstance(modalElement),list=document.getElementById('champions-modal-list'),title=document.getElementById('champions-modal-title');document.querySelectorAll('.show-champions').forEach(button=>button.addEventListener('click',()=>{const rows=champions[button.dataset.key]||[];title.textContent=button.dataset.name;list.innerHTML=rows.length?rows.map(item=>`<article class="champion-modal-row"><div class="champion-shield">${item.escudo_url?`<img src="${escapeHtml(item.escudo_url)}" alt="">`:`<span>${escapeHtml(initials(item.clube||item.tecnico))}</span>`}</div><div class="champion-modal-copy"><strong>${escapeHtml(item.clube||item.tecnico)}</strong><small>Técnico ${escapeHtml(item.tecnico||'—')}</small><span>${escapeHtml(item.titulo)}</span></div><b>${escapeHtml(item.temporada)}</b></article>`).join(''):'<p class="empty-champion text-center py-4">Nenhum campeão cadastrado ainda.</p>';modal.show()}));</script></body></html>
