<?php
declare(strict_types=1);
require __DIR__.'/includes/bootstrap.php';
require __DIR__.'/includes/public-layout.php';
$identities=[];$titles=[];
try {
    $pdo=db(); competition_identities_seed($pdo);
    $identities=$pdo->query("SELECT i.id,i.chave,i.nome FROM competicao_identidades i WHERE COALESCE(i.trofeu_base64,'')<>'' ORDER BY i.nome")->fetchAll();
    $titles=$pdo->query("SELECT t.id,t.titulo,t.temporada,t.conquistado_em,COALESCE(p.nome,t.tecnico_nome) tecnico,COALESCE(p.time_nome,t.time_nome) clube FROM titulos t LEFT JOIN participantes p ON p.id=t.participante_id ORDER BY t.conquistado_em DESC,t.id DESC")->fetchAll();
} catch(Throwable $ignored) {}
$grouped=[]; foreach($titles as $title){$key=competition_identity_match((string)$title['titulo']);if($key)$grouped[$key][]=$title;}
?><!doctype html><html lang="pt-BR" data-bs-theme="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vitrine de Títulos | Vascão S3</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css"><link rel="stylesheet" href="assets/css/branding.css?v=5"><link rel="stylesheet" href="assets/css/titles-showcase.css?v=<?= filemtime(__DIR__.'/assets/css/titles-showcase.css') ?>"></head><body><?php public_navbar('titulos'); ?><main class="titles-page"><div class="container"><header class="titles-hero"><span class="eyebrow">Salão de conquistas</span><h1>VITRINE DE TAÇAS</h1><p>Cada competição tem sua própria história. Explore as taças em tamanho grande e revele os campeões de todas as edições.</p></header><section class="trophy-showcase"><?php foreach($identities as $identity): $champions=$grouped[$identity['chave']]??[]; ?><article class="trophy-card"><div class="trophy-stage"><img src="api/competicao-imagem.php?identidade_id=<?= (int)$identity['id'] ?>&tipo=trofeu" alt="Taça <?= e($identity['nome']) ?>"></div><div class="trophy-copy"><img class="trophy-logo" src="api/competicao-imagem.php?identidade_id=<?= (int)$identity['id'] ?>&tipo=logo" alt="Logo <?= e($identity['nome']) ?>"><h2><?= e($identity['nome']) ?></h2><small class="text-secondary"><?= count($champions) ?> título<?= count($champions)===1?'':'s' ?> registrado<?= count($champions)===1?'':'s' ?></small><button class="btn btn-outline-light show-champions" type="button">VER CAMPEÕES</button><div class="champions-list"><?php if($champions): foreach($champions as $champion): ?><div class="champion-row"><span><strong><?= e($champion['clube']?:$champion['tecnico']) ?></strong><small class="d-block"><?= e($champion['titulo']) ?></small></span><small><?= e($champion['temporada']) ?></small></div><?php endforeach; else: ?><p class="empty-champion">Nenhum campeão cadastrado ainda.</p><?php endif; ?></div></div></article><?php endforeach; ?></section></div></main><?php public_footer(); ?><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"></script><script>document.querySelectorAll('.show-champions').forEach(button=>button.addEventListener('click',()=>{const card=button.closest('.trophy-card'),open=card.classList.toggle('is-open');button.textContent=open?'OCULTAR CAMPEÕES':'VER CAMPEÕES'}));</script></body></html>
