<?php
declare(strict_types=1);
require __DIR__.'/../includes/bootstrap.php';
require __DIR__.'/../includes/statistics.php';
$pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$pdo->sqliteCreateFunction('CONCAT',static fn(...$parts)=>implode('',$parts));$pdo->sqliteCreateFunction('IF',static fn($condition,$yes,$no)=>$condition?$yes:$no);
$pdo->exec("CREATE TABLE campeonatos(id INTEGER,nome TEXT,data_inicio TEXT,tipo TEXT,status TEXT,ativo INTEGER);CREATE TABLE participantes(id INTEGER,nome TEXT,time_nome TEXT,sigla TEXT,escudo_url TEXT,ativo INTEGER);CREATE TABLE partidas(id INTEGER,campeonato_id INTEGER,rodada INTEGER,mandante_id INTEGER,visitante_id INTEGER,gols_mandante INTEGER,gols_visitante INTEGER,data_partida TEXT,status TEXT,ativo INTEGER);CREATE TABLE jogos_mata_mata(id INTEGER,campeonato_id INTEGER,fase TEXT,ordem INTEGER,jogo INTEGER,time_a_id INTEGER,time_b_id INTEGER,gols_a INTEGER,gols_b INTEGER,penaltis_a INTEGER,penaltis_b INTEGER,vencedor_id INTEGER,status TEXT,ativo INTEGER,criado_em TEXT);CREATE TABLE gols_partida(partida_id INTEGER,participante_id INTEGER,jogador TEXT,tipo TEXT);CREATE TABLE gols_mata_mata(jogo_mata_mata_id INTEGER,participante_id INTEGER,jogador TEXT,tipo TEXT);CREATE TABLE sumulas_dreamteam(origem TEXT,partida_id INTEGER,jogo_mata_mata_id INTEGER,dados_json TEXT);CREATE TABLE movimentacoes_elenco_geral(id INTEGER,participante_id INTEGER,tipo TEXT,jogador_nome TEXT,valor REAL,criado_em TEXT);CREATE TABLE movimentacoes_elenco(id INTEGER,campeonato_id INTEGER,participante_id INTEGER,tipo TEXT,jogador_nome TEXT,valor REAL,criado_em TEXT);CREATE TABLE clubes_gerais(participante_id INTEGER,saldo REAL);CREATE TABLE clubes_campeonato(campeonato_id INTEGER,participante_id INTEGER,saldo REAL)");
$pdo->exec("INSERT INTO campeonatos VALUES(1,'Liga','2026-01-01','pontos_corridos','finalizado',1);INSERT INTO participantes VALUES(1,'Técnico A','Clube A','A','',1),(2,'Técnico B','Clube B','B','',1);INSERT INTO partidas VALUES(1,1,1,1,2,3,1,'2026-01-02','finalizada',1),(2,1,2,2,1,2,2,'2026-01-03','finalizada',1),(3,1,3,1,2,NULL,NULL,'2026-01-04','agendada',1);INSERT INTO gols_partida VALUES(1,1,'Atacante','normal'),(1,1,'Atacante','penalti'),(1,2,'Rival','normal');INSERT INTO sumulas_dreamteam VALUES('pontos',1,NULL,'{\"events\":[{\"type\":\"goal\",\"player\":\"Atacante\",\"team_code\":\"A\",\"goal_type\":\"tesoura\",\"cancelled\":false}]}');INSERT INTO movimentacoes_elenco_geral VALUES(1,1,'compra','Atacante',500,'2026-01-01');INSERT INTO clubes_gerais VALUES(1,1000),(2,700)");
$matches=statistics_matches($pdo);if(count($matches)!==2)throw new RuntimeException('Partidas futuras entraram no histórico.');
$teams=statistics_team_aggregates($matches);$a=array_values(array_filter($teams,fn($t)=>$t['id']===1))[0];if($a['wins']!==1||$a['draws']!==1||$a['gf']!==5||$a['ga']!==3)throw new RuntimeException('Agregado de clube incorreto.');
$pairs=statistics_head_to_head($matches);if($pairs[0]['games']!==2||$pairs[0]['total_goals']!==8)throw new RuntimeException('Retrospecto incorreto.');
$players=statistics_players($pdo);$scorer=array_values(array_filter($players,fn($p)=>$p['name']==='Atacante'))[0];if($scorer['goals']!==2||$scorer['penalties']!==1||($scorer['goal_types']['penalti']??0)!==1||($scorer['goal_types']['tesoura']??0)!==1)throw new RuntimeException('Ranking de jogadores incorreto.');
$finance=statistics_finance($pdo);if(count($finance['moves'])!==1||(float)$finance['clubs'][0]['spent']!==500.0)throw new RuntimeException('Financeiro incorreto.');
$pdo->exec("INSERT INTO campeonatos VALUES(2,'Copa','2026-02-01','mata_mata','finalizado',1);INSERT INTO participantes VALUES(3,'Técnico C','Clube C','C','',1),(4,'Técnico D','Clube D','D','',1);INSERT INTO jogos_mata_mata VALUES(1,2,'Final',1,1,1,2,1,0,NULL,NULL,1,'finalizado',1,'2026-02-10'),(2,2,'Terceiro lugar',1,1,3,4,2,1,NULL,NULL,3,'finalizado',1,'2026-02-09')");
$placements=statistics_competition_placements($pdo);$byClub=[];foreach($placements as $placement)$byClub[$placement['club_id']]=$placement;
if($byClub[2]['runner_ups']!==2||$byClub[1]['finals']!==1||$byClub[3]['thirds']!==1||$byClub[4]['fourths']!==1)throw new RuntimeException('Pódios e finais incorretos.');
echo "OK: partidas, clubes, retrospectos, jogadores e financeiro.\n";
